apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: your-dockerhub-username/product-service
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              value: "3004"
            - name: MONGO_URI
              value: "mongodb://admin:admin@host.docker.internal:27017"
            - name: USER_SERVICE_URL
              value: "http://user-service:3001"
            - name: JWT_SECRET
              value: "JWTkey123!"
            - name: KAFKA_BROKER
              value: "kafka:9092"
